### ISSUE TITLE
Why pubsub is not supported and is there any challenge in supporting it?

### ISSUE THREAD

**Issue by shyamnayak6** [Netflix/dynomite#548] opened 2018-03-12 11:53 UTC
Hi,

Our application mostly depends upon pubsub mechanism. As Dynomite does not support it, would you clarify if there is any challenge in supporting it. Is it possible to support it in future ?

Thanks,
Shyam

**Comment by shailesh33** [comment] 2018-03-16 21:28
The problem is propagating changes from all the nodes and funnelling it to a single client. If the co-ordinator node dies, the client shoudl connect to some other node. More importantly, the pub-sub occupies a connection to the data store. when we thought about this there was only one connection from dynomite to redis. That is not the case anymore but still this can be someone challenging. Ofcourse not impossible.

**Comment by ipapapa** [comment] 2018-03-26 18:06
Seems the question has been answered and there has not been a follow-up -> closing it.

**Closed as completed by ipapapa** 2018-03-26 18:06 UTC
Labels: Question
