### ISSUE TITLE
Invalid Argument Error

### ISSUE THREAD

**Issue by Bodenhaltung** [Netflix/dynomite#188] opened 2015-11-13 20:28 UTC
Hi,

i am not sure is this a issue, Debug Log:

```
2015-11-13 15:32:1.524] dnode_accept:297 dyn: accept on sd  9
[2015-11-13 15:32:1.524] dnode_accept:302 Accepting client connection from 0.0.0.0/0 on sd 9
[2015-11-13 15:32:1.524] dnode_accept:346 dyn: accepted c 9 on p 7 from '10.6.129.33:45663'
[2015-11-13 15:32:2.660] proxy_accept:351 accepted c 10 on p 6 from '10.6.129.33:47145'
[2015-11-13 15:32:2.660] _msg_get:262 alloc_msg_count : 1
[2015-11-13 15:32:2.661] dnode_peer_connect:1043 dnode: connected to peer '10.6.129.33:8101:r1:dc1:3867426167' on p 11
[2015-11-13 15:32:2.661] _msg_get:262 alloc_msg_count : 2
[2015-11-13 15:32:2.661] dnode_rsp_forward_match:117 req 4:6 with DC_ONE consistency is not being swallowed
[2015-11-13 15:32:2.661] dnode_rsp_forward_match:117 req -194321521:14593700 with DC_ONE consistency is not being swallowed
[2015-11-13 15:32:2.662] core_close_log:290 close CLIENT 10 '10.6.129.33:47145' on event 00FF eof 0 done 0 rb 159 sb 10: Invalid argument
[2015-11-13 15:32:2.662] client_unref_internal_try_put:119 unref conn 0xdeab60 owner 0xdcf860 from pool 'redis_cluster'
```

I dont understand why i get a "invalid argument".

Node 1 Config
```
  env: network
  listen: 10.6.129.32:8102
  dyn_listen: 10.6.129.32:8101
  tokens: '12345678'
  dyn_seeds:
    - 10.6.129.33:8101:r1:dc1:12345679
  servers:
  - 127.0.0.1:6379:1
  data_store: 0
  rack: r1
  datacenter: dc1
  secure_server_option: datacenter
  pem_key_file: /opt/dynomite/conf/dynomite.pem
```

Node 2 Config
```
  env: network
  listen: 10.6.129.33:8102
  dyn_listen: 10.6.129.33:8101
  tokens: '12345679'
  dyn_seeds:
    - 10.6.129.32:8101:r1:dc1:12345678
  servers:
  - 127.0.0.1:6379:1
  data_store: 0
  rack: r1
  datacenter: dc1
  secure_server_option: datacenter
  pem_key_file: /opt/dynomite/conf/dynomite.pem
```

Can someone please help me to find my mistake?

**Comment by shailesh33** [comment] 2015-11-13 20:33
Hi
Can you tell what is the command that you are sending?

**Comment by Bodenhaltung** [comment] 2015-11-13 20:40
Hi,

it is a php session:
````
session.save_handler = redis
session.save_path = "tcp://10.6.129.32:8102"
````

**Comment by shailesh33** [comment] 2015-11-13 21:04
I mean what is the redis operation? Get, Set etc?

**Comment by Bodenhaltung** [comment] 2015-11-13 21:25
Ah, SET.

**Comment by shailesh33** [comment] 2015-11-13 21:46
Looks like a basic thing, let me try it on my end, meanwhile try running your dynomite with -v9 or -v6 and see if you get any thing from teh logs. 

Even try disconnecting and reconnecting and trying again.

**Comment by shailesh33** [comment] 2015-11-19 23:06
Hi Why are your tokens like this? Shouldnt they be 
  tokens: '12345678'
and   tokens: '1383429731' ?

I tried with yaml files similar to yours, it worked for me. Can you run the dynomite with -v9 option and see if you find anything suspicious ?
Also try with 0.5.4 and let me know if it works in that version.

**Comment by Bodenhaltung** [comment] 2015-11-20 16:15
Hi, my fault, i have changed the tokens to node1: 2593449065 and node2: 3867426167 (maxint / nodecount).

In 0.5.4 the same "problem" i guess that the problem is the redis "QUIT" answer:
```
[Fri Nov 20 17:12:47 2015] mbuf_insert:214 insert mbuf 0x1443a10 len 0
[Fri Nov 20 17:12:47 2015] conn_recv:528 recv on sd 11 4 of 16320
[Fri Nov 20 17:12:47 2015] redis_parse_req:1789 parsed bad req 96 res 1 type 0 state 0
00000000  51 55 49 54                                        |QUIT|
[Fri Nov 20 17:12:47 2015] core_recv:257 recv on c 11 failed: Invalid argument
[Fri Nov 20 17:12:47 2015] core_close_log:312 close c 11 '10.6.129.32:34544' on event 00FF eof 0 done 0 rb 160 sb 23: Invalid argument
[Fri Nov 20 17:12:47 2015] client_close:183 close c 11 discarding pending req 96 len 4 type 0
[Fri Nov 20 17:12:47 2015] msg_put:531 put msg 0x142aa70 id 96
[Fri Nov 20 17:12:47 2015] mbuf_remove:237 remove mbuf 0x1443a10 len 4
[Fri Nov 20 17:12:47 2015] mbuf_put:153 put mbuf 0x1443a10 len 4
[Fri Nov 20 17:12:47 2015] _dn_free:299 free(0x142a830) @ dyn_dict.c:470
[Fri Nov 20 17:12:47 2015] _dn_free:299 free(0x144bde0) @ dyn_dict.c:482
[Fri Nov 20 17:12:47 2015] client_unref:101 unref conn 0x142a8a0 owner 0x1418860 from pool 'redis_cluster'
```

**Comment by shailesh33** [comment] 2015-11-20 16:22
I believe quit is supported. I am not near a computer right now, the lower
case quit

**Comment by shailesh33** [comment] 2015-11-23 22:03
Hi THe problem is you are not using the new binary redis protocol. I tried this command locally:
127.0.0.1:8102> set abc def
OK

THis is what I see in the logs: 
[2015-11-23 14:03:0.313] redis_parse_req:1779 parsed req 11 res 0 type 54 state 0 rpos 31 of 31
00000000  2a 33 0d 0a 24 33 0d 0a  73 65 74 0d 0a 24 33 0d   |*3..$3..set..$3.|
00000010  0a 61 62 63 0d 0a 24 33  0d 0a 64 65 66 0d 0a      |.abc..$3..def..|

**Comment by ipapapa** [comment] 2016-10-13 00:20
I am closing this as there has not been much activity and it seems it works based on @shailesh33 response. If there is any problem, let us know and we can reopen it.

**Closed by ipapapa** 2016-10-13 00:20 UTC
Labels: question
