### ISSUE TITLE
Memory leak in dynomite?

### ISSUE THREAD

**Issue by gauxs** [Netflix/dynomite#635] opened 2019-02-16 07:50 UTC
I have take two machines and ran dynomite in them using below config yaml:

DC-1 yaml file-
dyn_o_mite:
  datacenter: VCS2112
  rack: rack1
  dyn_listen: 10.5.95.140:7379
  dyn_seeds:
  - 10.5.75.45:7379:rack1:VCS2887:0
  listen: 0.0.0.0:8379
  servers:
  - 127.0.0.1:6379:1
  tokens: '0'
  data_store: 0

NOTE: The text is getting formatted here but assume yaml format is correct.

DC-2 yaml file:
dyn_o_mite:
  datacenter: VCS2887
  rack: rack1
  dyn_listen: 10.5.75.45:7379
  dyn_seeds:
  - 10.5.95.140:7379:rack1:VCS2112:0
  listen: 0.0.0.0:8379
  servers:
  - 127.0.0.1:6379:1
  tokens: '0'
  data_store: 0

I wrote a bash script to add 40k hash entries in one of the machine which was then replicated to the other machine. The problem i am facing is that i can see the memory consumption for dynomite process constantly shooting up with each 40k add and 40k delete of the same keys. Any reason why? Is this a memory leak and how to avoid this?

Before addition of redis-keys:
![image](https://user-images.githubusercontent.com/5405553/52896402-6ef3ea80-31ed-11e9-8d99-96a9e75f786a.png)

After addition of redis-keys:
![image](https://user-images.githubusercontent.com/5405553/52896406-7d420680-31ed-11e9-89f6-47cf29727109.png)

After deletion of the keys added previously:
![image](https://user-images.githubusercontent.com/5405553/52896411-9054d680-31ed-11e9-9885-25196d654462.png)

**Comment by gauxs** [comment] 2019-02-16 08:03
I ran again with mbuf_size: 16384 and max_msgs: 300000, but see the same problem of memory consumption increasing. Shouldn't the memory be free after the delete happens?

Also i see this message in logs:
![image](https://user-images.githubusercontent.com/5405553/52896526-70261700-31ef-11e9-8480-ce5088652bb9.png)

**Comment by gauxs** [comment] 2019-02-17 05:32
ran it with max_msgs:100000 still memory only shoots up.

**Comment by smukil** [comment] 2019-03-05 02:10
@gau0522 Sorry for the slow reply. Didn't notice the issue notifications. Dynomite follows a "allocate once and don't free" principal. So, once MBUFs are allocated, they're not freed so that future queries can run faster by not allocating memory again.

We don't consider this a problem as we cap the amount of memory that dynomite can use, so that dynomite does not starve the other processes on the node (notably Redis) of memory. This _may_ change in the future, however, to have a more robust memory manager, but this isn't a pain point in the system currently.

Closing this, as this is expected behavior by design. Please reopen if you have further queries.

**Closed as completed by smukil** 2019-03-05 02:10 UTC

**Comment by reoxey** [comment] 2019-07-24 10:41
@smukil So, how do we cap the amount of memory used by dynomite?
